"""Generate the check-in LaunchAgents from `user.yaml`.

Config is the source of truth; the plists are generated from it. Hand-edited
plists drift from config and nobody notices until a prompt stops arriving.

Two scheduled jobs failed silently on 2026-08-24 and both failure modes are
designed out here:

- One pointed at `/opt/homebrew/bin/uv`, which does not exist on this machine.
  The uv path is resolved at generation time, not guessed.
- One ran against a working tree sitting on a feature branch, so the script it
  wanted was simply absent. `WorkingDirectory` is pinned explicitly, and the
  runner Telegrams on failure rather than exiting into an empty log file.
"""
from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

from pa_core.config import PA_ROOT, get_user_config

SLOTS = ("morning", "evening")
LAUNCH_AGENTS = Path.home() / "Library" / "LaunchAgents"
DEFAULT_TIMES = {"morning": "06:30", "evening": "21:00"}


def parse_time(value) -> tuple[int, int]:
    """"HH:MM" → (hour, minute). Raises rather than defaulting to midnight.

    A typo'd time silently becoming 00:00 would send the morning prompt in the
    middle of the night, which is worse than a loud failure at setup.
    """
    if not isinstance(value, str) or ":" not in value:
        raise ValueError(f"Check-in time must look like 'HH:MM', got {value!r}")
    hh, _, mm = value.partition(":")
    hour, minute = int(hh), int(mm)
    if not (0 <= hour <= 23 and 0 <= minute <= 59):
        raise ValueError(f"Check-in time out of range: {value!r}")
    return hour, minute


def resolve_uv() -> str:
    """Absolute path to uv. Never assume Homebrew."""
    found = shutil.which("uv")
    if not found:
        raise RuntimeError("uv not found on PATH — cannot generate a working LaunchAgent")
    return found


def build_plist(slot: str, time_str: str, uv: str, repo: str) -> str:
    hour, minute = parse_time(time_str)
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.pa.wellness-{slot}</string>

    <!-- GENERATED by `pa-core schedule-checkins` from user.yaml. Do not edit by
         hand: the next run will overwrite it. Change `checkins.{slot}` in
         user.yaml and re-run instead. -->

    <key>ProgramArguments</key>
    <array>
        <string>{uv}</string>
        <string>run</string>
        <string>python</string>
        <string>scripts/wellness_prompt.py</string>
        <string>--{slot}</string>
    </array>

    <key>WorkingDirectory</key>
    <string>{repo}</string>

    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key><integer>{hour}</integer>
        <key>Minute</key><integer>{minute}</integer>
    </dict>

    <!-- Loading the agent must not fire an unexpected prompt at the wrong hour. -->
    <key>RunAtLoad</key>
    <false/>

    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>{Path(uv).parent}:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
    </dict>

    <key>StandardOutPath</key>
    <string>/tmp/wellness-{slot}.out</string>
    <key>StandardErrorPath</key>
    <string>/tmp/wellness-{slot}.err</string>
</dict>
</plist>
"""


def install(reload: bool = True) -> list[str]:
    """Write and load both plists from config. Returns what it did."""
    config = get_user_config()
    times = {**DEFAULT_TIMES, **(config.get("checkins") or {})}
    uv = resolve_uv()
    repo = str(PA_ROOT)
    LAUNCH_AGENTS.mkdir(parents=True, exist_ok=True)

    done = []
    for slot in SLOTS:
        time_str = times[slot]
        parse_time(time_str)  # fail loudly before writing anything
        path = LAUNCH_AGENTS / f"com.pa.wellness-{slot}.plist"
        path.write_text(build_plist(slot, time_str, uv, repo))
        if reload:
            subprocess.run(["launchctl", "unload", str(path)],
                           capture_output=True, check=False)
            subprocess.run(["launchctl", "load", "-w", str(path)],
                           capture_output=True, check=False)
        done.append(f"{slot} check-in at {time_str} → {path.name}")
    return done
